use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct MetricsResponse {
    pub(crate) total_packets: u64,
    pub(crate) blocked_packets: u64,
    pub(crate) blocked_l4: u64,
    pub(crate) blocked_l7: u64,
    pub(crate) l7_cc_challenges: u64,
    pub(crate) l7_cc_blocks: u64,
    pub(crate) l7_cc_delays: u64,
    pub(crate) l7_cc_unresolved_identity_delays: u64,
    pub(crate) l7_cc_verified_passes: u64,
    pub(crate) total_bytes: u64,
    pub(crate) proxied_requests: u64,
    pub(crate) proxy_successes: u64,
    pub(crate) proxy_failures: u64,
    pub(crate) proxy_fail_close_rejections: u64,
    pub(crate) l4_bucket_budget_rejections: u64,
    pub(crate) tls_pre_handshake_rejections: u64,
    pub(crate) trusted_proxy_permit_drops: u64,
    pub(crate) trusted_proxy_l4_degrade_actions: u64,
    pub(crate) tls_handshake_timeouts: u64,
    pub(crate) tls_handshake_failures: u64,
    pub(crate) upstream_healthcheck_successes: u64,
    pub(crate) upstream_healthcheck_failures: u64,
    pub(crate) proxy_latency_micros_total: u64,
    pub(crate) average_proxy_latency_micros: u64,
    pub(crate) active_rules: u64,
    pub(crate) sqlite_enabled: bool,
    pub(crate) persisted_security_events: u64,
    pub(crate) persisted_blocked_ips: u64,
    pub(crate) persisted_rules: u64,
    pub(crate) sqlite_queue_capacity: u64,
    pub(crate) sqlite_queue_depth: u64,
    pub(crate) sqlite_dropped_security_events: u64,
    pub(crate) sqlite_dropped_blocked_ips: u64,
    pub(crate) last_persisted_event_at: Option<i64>,
    pub(crate) last_rule_update_at: Option<i64>,
    pub(crate) l4_bucket_count: u64,
    pub(crate) l4_fine_grained_buckets: u64,
    pub(crate) l4_coarse_buckets: u64,
    pub(crate) l4_peer_only_buckets: u64,
    pub(crate) l4_high_risk_buckets: u64,
    pub(crate) l4_behavior_dropped_events: u64,
    pub(crate) l4_overload_level: String,
}

#[derive(Debug, Serialize)]
pub struct L4StatsResponse {
    pub(crate) enabled: bool,
    pub(crate) behavior: crate::l4::behavior::L4BehaviorSnapshot,
    pub(crate) connections: crate::l4::connection::ConnectionStats,
    pub(crate) ddos_events: u64,
    pub(crate) protocol_anomalies: u64,
    pub(crate) traffic: u64,
    pub(crate) defense_actions: u64,
    pub(crate) bloom_stats: Option<crate::l4::bloom_filter::L4BloomStats>,
    pub(crate) false_positive_stats: Option<crate::l4::bloom_filter::L4FalsePositiveStats>,
    pub(crate) per_port_stats: Vec<crate::l4::inspector::PortStats>,
}

#[derive(Debug, Serialize)]
pub struct L7StatsResponse {
    pub(crate) enabled: bool,
    pub(crate) blocked_requests: u64,
    pub(crate) cc_challenge_requests: u64,
    pub(crate) cc_block_requests: u64,
    pub(crate) cc_delayed_requests: u64,
    pub(crate) cc_unresolved_identity_delayed_requests: u64,
    pub(crate) cc_verified_pass_requests: u64,
    pub(crate) proxied_requests: u64,
    pub(crate) proxy_successes: u64,
    pub(crate) proxy_failures: u64,
    pub(crate) proxy_fail_close_rejections: u64,
    pub(crate) l4_bucket_budget_rejections: u64,
    pub(crate) tls_pre_handshake_rejections: u64,
    pub(crate) trusted_proxy_permit_drops: u64,
    pub(crate) trusted_proxy_l4_degrade_actions: u64,
    pub(crate) tls_handshake_timeouts: u64,
    pub(crate) tls_handshake_failures: u64,
    pub(crate) average_proxy_latency_micros: u64,
    pub(crate) upstream_healthy: bool,
    pub(crate) upstream_last_check_at: Option<i64>,
    pub(crate) upstream_last_error: Option<String>,
    pub(crate) http3_feature_available: bool,
    pub(crate) http3_configured_enabled: bool,
    pub(crate) http3_tls13_enabled: bool,
    pub(crate) http3_certificate_configured: bool,
    pub(crate) http3_private_key_configured: bool,
    pub(crate) http3_listener_started: bool,
    pub(crate) http3_listener_addr: Option<String>,
    pub(crate) http3_status: String,
    pub(crate) http3_last_error: Option<String>,
    pub(crate) auto_tuning: AutoTuningRuntimeResponse,
}

#[derive(Debug, Serialize)]
pub struct AutoTuningRuntimeResponse {
    pub(crate) mode: String,
    pub(crate) intent: String,
    pub(crate) controller_state: String,
    pub(crate) detected_cpu_cores: usize,
    pub(crate) detected_memory_limit_mb: Option<u64>,
    pub(crate) last_adjust_at: Option<i64>,
    pub(crate) last_adjust_reason: Option<String>,
    pub(crate) last_adjust_diff: Vec<String>,
    pub(crate) rollback_count_24h: u32,
    pub(crate) cooldown_until: Option<i64>,
    pub(crate) last_effect_evaluation: Option<AutoTuningEffectEvaluationResponse>,
    pub(crate) last_observed_tls_handshake_timeout_rate_percent: f64,
    pub(crate) last_observed_bucket_reject_rate_percent: f64,
    pub(crate) last_observed_avg_proxy_latency_ms: u64,
    pub(crate) recommendation: AutoTuningRecommendationResponse,
}

#[derive(Debug, Serialize)]
pub struct AutoTuningEffectEvaluationResponse {
    pub(crate) status: String,
    pub(crate) observed_at: Option<i64>,
    pub(crate) sample_requests: u64,
    pub(crate) handshake_timeout_rate_delta_percent: f64,
    pub(crate) bucket_reject_rate_delta_percent: f64,
    pub(crate) avg_proxy_latency_delta_ms: i64,
    pub(crate) summary: String,
}

#[derive(Debug, Serialize)]
pub struct AutoTuningRecommendationResponse {
    pub(crate) l4_normal_connection_budget_per_minute: u32,
    pub(crate) l4_suspicious_connection_budget_per_minute: u32,
    pub(crate) l4_high_risk_connection_budget_per_minute: u32,
    pub(crate) l4_reject_threshold_percent: u16,
    pub(crate) l4_critical_reject_threshold_percent: u16,
    pub(crate) tls_handshake_timeout_ms: u64,
}
