use super::auth::admin_auth_middleware;
use super::events_handlers;
use super::realtime;
use super::safeline_handlers;
use super::settings_handlers;
use super::sites_handlers;
use super::state::ApiState;
use super::system_handlers;
use axum::{
    middleware,
    routing::{delete, get, patch, post},
    Router,
};

pub(super) fn build_router(state: ApiState) -> Router {
    let protected = Router::new()
        .route("/metrics", get(system_handlers::metrics_handler))
        .route(
            "/ws/admin-ticket",
            axum::routing::post(realtime::issue_admin_ws_ticket_handler),
        )
        .route(
            "/dashboard/traffic-map",
            get(system_handlers::traffic_map_handler),
        )
        .route(
            "/dashboard/ai-audit-summary",
            get(system_handlers::ai_audit_summary_handler),
        )
        .route(
            "/dashboard/ai-audit-report",
            get(system_handlers::ai_audit_report_handler),
        )
        .route(
            "/dashboard/ai-auto-audit-status",
            get(system_handlers::ai_auto_audit_status_handler),
        )
        .route(
            "/dashboard/ai-audit-report/run",
            post(system_handlers::run_ai_audit_report_handler),
        )
        .route(
            "/dashboard/ai-audit-reports",
            get(system_handlers::list_ai_audit_reports_handler),
        )
        .route(
            "/dashboard/ai-audit-reports/:id/feedback",
            patch(system_handlers::update_ai_audit_report_feedback_handler),
        )
        .route(
            "/dashboard/ai-temp-policies",
            get(system_handlers::list_ai_temp_policies_handler),
        )
        .route(
            "/dashboard/ai-temp-policies/:id",
            delete(system_handlers::delete_ai_temp_policy_handler),
        )
        .route(
            "/l4/config",
            get(settings_handlers::get_l4_config_handler)
                .put(settings_handlers::update_l4_config_handler),
        )
        .route("/l4/stats", get(settings_handlers::get_l4_stats_handler))
        .route(
            "/l7/config",
            get(settings_handlers::get_l7_config_handler)
                .put(settings_handlers::update_l7_config_handler),
        )
        .route("/l7/stats", get(settings_handlers::get_l7_stats_handler))
        .route(
            "/settings",
            get(settings_handlers::get_settings_handler)
                .put(settings_handlers::update_settings_handler),
        )
        .route(
            "/global-settings",
            get(settings_handlers::get_global_settings_handler)
                .put(settings_handlers::update_global_settings_handler),
        )
        .route(
            "/events",
            get(events_handlers::list_security_events_handler),
        )
        .route(
            "/behavior/profiles",
            get(events_handlers::list_behavior_profiles_handler),
        )
        .route(
            "/intelligence/fingerprints",
            get(events_handlers::list_fingerprint_profiles_handler),
        )
        .route(
            "/intelligence/sessions",
            get(events_handlers::list_behavior_sessions_handler),
        )
        .route(
            "/events/:id",
            patch(events_handlers::update_security_event_handler),
        )
        .route(
            "/blocked-ips",
            get(events_handlers::list_blocked_ips_handler)
                .post(events_handlers::create_blocked_ip_handler),
        )
        .route(
            "/blocked-ips/unblock-batch",
            post(events_handlers::batch_unblock_blocked_ips_handler),
        )
        .route(
            "/blocked-ips/cleanup-expired",
            post(events_handlers::cleanup_expired_blocked_ips_handler),
        )
        .route(
            "/blocked-ips/:id",
            delete(events_handlers::delete_blocked_ip_handler),
        )
        .route(
            "/sites/local",
            get(sites_handlers::list_local_sites_handler)
                .post(sites_handlers::create_local_site_handler),
        )
        .route(
            "/sites/global-entry",
            get(sites_handlers::get_global_entry_config_handler)
                .put(sites_handlers::update_global_entry_config_handler),
        )
        .route(
            "/sites/local/reset",
            axum::routing::post(sites_handlers::clear_local_site_data_handler),
        )
        .route(
            "/sites/local/:id",
            get(sites_handlers::get_local_site_handler)
                .put(sites_handlers::update_local_site_handler)
                .delete(sites_handlers::delete_local_site_handler),
        )
        .route(
            "/certificates/local",
            get(sites_handlers::list_local_certificates_handler)
                .post(sites_handlers::create_local_certificate_handler),
        )
        .route(
            "/certificates/local/generate",
            axum::routing::post(sites_handlers::generate_local_certificate_handler),
        )
        .route(
            "/certificates/local/:id",
            get(sites_handlers::get_local_certificate_handler)
                .put(sites_handlers::update_local_certificate_handler)
                .delete(sites_handlers::delete_local_certificate_handler),
        )
        .route(
            "/certificates/local/:id/remote-binding",
            axum::routing::post(sites_handlers::bind_local_certificate_remote_handler)
                .delete(sites_handlers::unbind_local_certificate_remote_handler),
        )
        .route(
            "/integrations/safeline/test",
            axum::routing::post(safeline_handlers::test_safeline_handler),
        )
        .route(
            "/integrations/safeline/sites",
            axum::routing::post(safeline_handlers::list_safeline_sites_handler),
        )
        .route(
            "/integrations/safeline/sites/cached",
            get(safeline_handlers::list_cached_safeline_sites_handler),
        )
        .route(
            "/integrations/safeline/mappings",
            get(safeline_handlers::list_safeline_mappings_handler)
                .put(safeline_handlers::update_safeline_mappings_handler),
        )
        .route(
            "/integrations/safeline/pull/sites",
            axum::routing::post(safeline_handlers::pull_safeline_sites_handler),
        )
        .route(
            "/integrations/safeline/pull/sites/:remote_site_id",
            axum::routing::post(safeline_handlers::pull_safeline_site_handler),
        )
        .route(
            "/integrations/safeline/push/sites",
            axum::routing::post(safeline_handlers::push_safeline_sites_handler),
        )
        .route(
            "/integrations/safeline/push/sites/:local_site_id",
            axum::routing::post(safeline_handlers::push_safeline_site_handler),
        )
        .route(
            "/integrations/safeline/pull/certificates",
            axum::routing::post(safeline_handlers::pull_safeline_certificates_handler),
        )
        .route(
            "/integrations/safeline/pull/certificates/:remote_cert_id",
            axum::routing::post(safeline_handlers::pull_safeline_certificate_handler),
        )
        .route(
            "/integrations/safeline/push/certificates/:local_certificate_id",
            axum::routing::post(safeline_handlers::push_safeline_certificate_handler),
        )
        .route(
            "/integrations/safeline/match/certificates/:local_certificate_id",
            axum::routing::post(safeline_handlers::preview_safeline_certificate_match_handler),
        )
        .route(
            "/integrations/safeline/site-links",
            get(safeline_handlers::list_site_sync_links_handler)
                .put(safeline_handlers::upsert_site_sync_link_handler),
        )
        .route(
            "/integrations/safeline/site-links/:id",
            delete(safeline_handlers::delete_site_sync_link_handler),
        )
        .route(
            "/integrations/safeline/sync/events",
            axum::routing::post(safeline_handlers::sync_safeline_events_handler),
        )
        .route(
            "/integrations/safeline/sync/state",
            get(safeline_handlers::get_safeline_sync_state_handler),
        )
        .route(
            "/integrations/safeline/sync/blocked-ips",
            axum::routing::post(safeline_handlers::sync_safeline_blocked_ips_handler),
        )
        .route(
            "/integrations/safeline/pull/blocked-ips",
            axum::routing::post(safeline_handlers::pull_safeline_blocked_ips_handler),
        )
        .merge(super::rules::router())
        .layer(middleware::from_fn_with_state(
            state.clone(),
            admin_auth_middleware,
        ));

    Router::new()
        .route("/health", get(system_handlers::health_handler))
        .route("/ws/admin", get(realtime::admin_ws_handler))
        .merge(protected)
        .with_state(state)
}
