import type { L7ConfigPayload } from '@/features/l7/types/l7'

export type L7ConfigForm = Omit<
  L7ConfigPayload,
  | 'runtime_enabled'
  | 'adaptive_managed_fields'
  | 'adaptive_runtime'
  | 'advanced_compatibility'
>

export const numberInputClass =
  'mt-2 w-full rounded-[18px] border border-slate-200 bg-white px-4 py-3 text-sm text-stone-800 outline-none transition focus:border-blue-500/40'

export const listFieldClass =
  'mt-2 min-h-[120px] w-full rounded-[18px] border border-slate-200 bg-white px-4 py-3 text-sm text-stone-800 outline-none transition focus:border-blue-500/40'

export function createDefaultL7ConfigForm(): L7ConfigForm {
  return {
    runtime_profile: 'standard',
    max_request_size: 8192,
    first_byte_timeout_ms: 2000,
    read_idle_timeout_ms: 5000,
    tls_handshake_timeout_ms: 3000,
    proxy_connect_timeout_ms: 1500,
    proxy_write_timeout_ms: 3000,
    proxy_read_timeout_ms: 10000,
    upstream_healthcheck_enabled: true,
    upstream_healthcheck_interval_secs: 5,
    upstream_healthcheck_timeout_ms: 1000,
    upstream_failure_mode: 'fail_open',
    upstream_protocol_policy: 'http2_preferred',
    upstream_http1_strict_mode: true,
    upstream_http1_allow_connection_reuse: false,
    reject_ambiguous_http1_requests: true,
    reject_http1_transfer_encoding_requests: true,
    reject_body_on_safe_http_methods: true,
    reject_expect_100_continue: true,
    bloom_filter_scale: 1,
    http2_enabled: true,
    http2_max_concurrent_streams: 100,
    http2_max_frame_size: 16384,
    http2_enable_priorities: true,
    http2_initial_window_size: 65535,
    bloom_enabled: true,
    bloom_false_positive_verification: true,
    listen_addrs: ['0.0.0.0:8080'],
    upstream_endpoint: '',
    http3_enabled: false,
    http3_listen_addr: '0.0.0.0:8443',
    http3_max_concurrent_streams: 100,
    http3_idle_timeout_secs: 300,
    http3_mtu: 1350,
    http3_max_frame_size: 65536,
    http3_enable_connection_migration: true,
    http3_qpack_table_size: 4096,
    http3_certificate_path: '',
    http3_private_key_path: '',
    http3_enable_tls13: true,
    cc_defense: {
      enabled: true,
      request_window_secs: 10,
      ip_challenge_threshold: 60,
      ip_block_threshold: 120,
      host_challenge_threshold: 48,
      host_block_threshold: 96,
      route_challenge_threshold: 24,
      route_block_threshold: 48,
      hot_path_challenge_threshold: 800,
      hot_path_block_threshold: 1600,
      delay_threshold_percent: 70,
      delay_ms: 150,
      challenge_ttl_secs: 1800,
      challenge_cookie_name: 'rwaf_cc',
      hard_route_block_multiplier: 4,
      hard_host_block_multiplier: 4,
      hard_ip_block_multiplier: 4,
      hard_hot_path_block_multiplier: 3,
    },
    slow_attack_defense: {
      enabled: true,
      header_min_bytes_per_sec: 64,
      body_min_bytes_per_sec: 256,
      idle_keepalive_timeout_ms: 5000,
      event_window_secs: 300,
      max_events_per_window: 6,
      block_duration_secs: 900,
    },
    safeline_intercept: {
      enabled: true,
      action: 'replace',
      match_mode: 'strict',
      max_body_bytes: 32768,
      block_duration_secs: 600,
      response_template: {
        status_code: 403,
        content_type: 'text/html; charset=utf-8',
        body_source: 'inline_text',
        gzip: false,
        body_text:
          '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>请求已拦截</title></head><body><h1>请求已拦截</h1><p>当前请求被上游安全策略拦截。</p></body></html>',
        body_file_path: '',
        headers: [{ key: 'cache-control', value: 'no-store' }],
      },
    },
    ip_access: {
      enabled: false,
      mode: 'domestic_only',
      default_action: 'allow',
      overseas_action: 'challenge',
      unknown_geo_action: 'challenge',
      allow_private_ips: true,
      allow_server_public_ip: true,
      domestic_country_codes: ['CN'],
      allow_cidrs: [],
      block_cidrs: [],
      domestic_cidrs: [],
      bot_policy: {
        allow_verified_search_bots: true,
        allow_claimed_search_bots: false,
        allow_ai_bots: false,
        claimed_search_bot_action: 'challenge',
        suspect_bot_action: 'challenge',
      },
      geo_headers: {
        enabled: true,
        trust_only_from_proxy: true,
        country_headers: [
          'cf-ipcountry',
          'cloudfront-viewer-country',
          'fastly-client-country-code',
          'x-geo-country',
          'x-client-country',
        ],
        region_headers: ['x-geo-region'],
        city_headers: ['x-geo-city'],
      },
    },
    auto_tuning: {
      mode: 'observe',
      intent: 'balanced',
      runtime_adjust_enabled: false,
      bootstrap_secs: 60,
      control_interval_secs: 30,
      cooldown_secs: 120,
      max_step_percent: 8,
      rollback_window_minutes: 10,
      pinned_fields: [],
      slo: {
        tls_handshake_timeout_rate_percent: 0.3,
        bucket_reject_rate_percent: 0.5,
        p95_proxy_latency_ms: 800,
      },
    },
  }
}
