use super::segments::ProxyTrafficSegmentSnapshot;

#[cfg_attr(not(feature = "api"), allow(dead_code))]
#[derive(Debug, Clone, Default)]
pub struct MetricsSnapshot {
    pub total_packets: u64,
    pub blocked_packets: u64,
    pub blocked_l4: u64,
    pub blocked_l7: u64,
    pub early_defense_drops_total: u64,
    pub early_defense_spoofed_forward_header_drops: u64,
    pub early_defense_trusted_cdn_unresolved_drops: u64,
    pub early_defense_l4_request_budget_drops: u64,
    pub early_defense_l4_high_risk_drops: u64,
    pub early_defense_l4_suspicious_drops: u64,
    pub early_defense_other_drops: u64,
    pub l7_drop_reason_cc_hot_block: u64,
    pub l7_drop_reason_cc_fast_block: u64,
    pub l7_drop_reason_cc_hard_block: u64,
    pub l7_drop_reason_spoofed_forward_header: u64,
    pub l7_drop_reason_behavior_aggregate: u64,
    pub l7_drop_reason_behavior_route_burst: u64,
    pub l7_drop_reason_l7_bloom_filter: u64,
    pub l7_drop_reason_blocked_client_ip: u64,
    pub l7_drop_reason_other: u64,
    pub l7_cc_challenges: u64,
    pub l7_cc_blocks: u64,
    pub l7_cc_delays: u64,
    pub l7_cc_unresolved_identity_delays: u64,
    pub l7_cc_verified_passes: u64,
    pub l7_cc_fast_path_requests: u64,
    pub l7_cc_fast_path_blocks: u64,
    pub l7_cc_fast_path_challenges: u64,
    pub l7_cc_fast_path_no_decisions: u64,
    pub l7_cc_hot_cache_hits: u64,
    pub l7_cc_hot_cache_misses: u64,
    pub l7_cc_hot_cache_expired: u64,
    pub l7_behavior_challenges: u64,
    pub l7_behavior_blocks: u64,
    pub l7_behavior_delays: u64,
    pub l7_ip_access_allows: u64,
    pub l7_ip_access_alerts: u64,
    pub l7_ip_access_challenges: u64,
    pub l7_ip_access_blocks: u64,
    pub l7_ip_access_verified_passes: u64,
    pub total_bytes: u64,
    pub proxied_requests: u64,
    pub proxy_successes: u64,
    pub proxy_failures: u64,
    pub proxy_fail_close_rejections: u64,
    pub l4_bucket_budget_rejections: u64,
    pub l4_request_budget_softened: u64,
    pub tls_pre_handshake_rejections: u64,
    pub trusted_proxy_permit_drops: u64,
    pub trusted_proxy_l4_degrade_actions: u64,
    pub tls_handshake_timeouts: u64,
    pub tls_handshake_failures: u64,
    pub slow_attack_idle_timeouts: u64,
    pub slow_attack_header_timeouts: u64,
    pub slow_attack_body_timeouts: u64,
    pub slow_attack_tls_handshake_hits: u64,
    pub slow_attack_blocks: u64,
    pub upstream_healthcheck_successes: u64,
    pub upstream_healthcheck_failures: u64,
    pub proxy_latency_micros_total: u64,
    pub average_proxy_latency_micros: u64,
    pub streamed_proxy_responses: u64,
    pub proxy_body_preview_truncations: u64,
    pub http2_pool_evictions: u64,
    pub document_proxy: ProxyTrafficMetricsSnapshot,
    pub api_proxy: ProxyTrafficMetricsSnapshot,
    pub static_proxy: ProxyTrafficMetricsSnapshot,
    pub other_proxy: ProxyTrafficMetricsSnapshot,
    pub top_host_segments: Vec<ProxyTrafficSegmentSnapshot>,
    pub top_route_segments: Vec<ProxyTrafficSegmentSnapshot>,
    pub top_host_route_segments: Vec<ProxyTrafficSegmentSnapshot>,
    pub l4_direct_idle_no_request_buckets: u64,
    pub l4_direct_idle_no_request_connections: u64,
}

#[derive(Debug, Clone, Default)]
pub struct ProxyTrafficMetricsSnapshot {
    pub proxied_requests: u64,
    pub proxy_successes: u64,
    pub proxy_failures: u64,
    pub average_proxy_latency_micros: u64,
}
